name 'local'
maintainer 'Ken Young'
maintainer_email 'kenzy@acm.org'
license 'apache2'
description 'Installs/Configures local'
long_description 'Installs/Configures local'
version '0.1.0'
depends 'winbox', '= 0.9.101'
